- src/com/yahoo/ml/tf/TFCluster.py
Looks like we can simplify cluster_spec build as the code change.
> Simplify cluster_spec build

- src/com/yahoo/ml/tf/TFSparkNode.py
The background mode invoke the TensorFlow main function in a background thread. However, this mode relies reuse of python worker in Spark.
The config of reuse of python worker in Spark is enabled by default. But we should add the check in case of disabled reuse of python worker.
Besides, reuse of python worker can't work on Windows. So background mode can't work on Windows. We should add necessary check for it too.
> Add few necessary checks for using background mode

- src/com/yahoo/ml/tf/TFNode.py
- src/com/yahoo/ml/tf/TFSparkNode.py
- expand hadoop classpath for Spark 2.x JNI
- modify terminate logic to avoid deadlock
> Fix Spark 2.x + HDFS hangs

- src/com/yahoo/ml/tf/TFCluster.py
- src/com/yahoo/ml/tf/TFSparkNode.py
- Detect dupes in cluster_info (e.g. host/ppid unique id for TFManagers).
- Detect stale TFSparkNode/TFManager via a new cluster_id.
> add error handling around TFCluster.reserve()

- src/com/yahoo/ml/tf/TFNode.py
Support read data from [ViewFs](http://hadoop.apache.org/docs/r2.6.5/hadoop-project-dist/hadoop-hdfs/ViewFs.html). This PR related to https://github.com/tensorflow/tensorflow/pull/8079
manual tests
> Support read data from ViewFs

- examples/mnist/spark/mnist_dist.py
- examples/mnist/spark/mnist_spark.py
- src/com/yahoo/ml/tf/TFNode.py
- src/com/yahoo/ml/tf/TFSparkNode.py
- src/com/yahoo/ml/tf/marker.py
in spark mode, inference task will be blocked if the partition size can't be divided exactly by batch
> inference task will be blocked in spark mode

- examples/mnist/TFOS_spark_demo.ipynb
> updated ipynb for spark standalone

- README.md
Currently "Shutdown" is not part of the list.
> Fix README.md nested list formatting.

- tensorflowonspark/reservation.py
- test/README.md
- test/run_tests.sh
- test/test.py
- test/test_TFCluster.py
- test/test_TFNode.py
- test/test_reservation.py
First pass to set up infrastructure w/ some basic tests.
Note: this includes a minor update to `reservation.py` to handle a corner case.
> Unit/Integration Tests

- examples/mnist/keras/README.md
- examples/mnist/keras/mnist_mlp.py
... to save standard TensorFlow model checkpoints (to bypass ModelCheckpoint/HDF5 issue)
> Updated keras example using LambdaCallback

- examples/mnist/streaming/mnist_spark.py
> increase spark streaming interval for examples

- examples/mnist/estimator/mnist_estimator.py
- tensorflowonspark/TFCluster.py
- tensorflowonspark/reservation.py
- add data_dir arg to mnist_estimator.py
- add assertion error msgs
> Minor updates

- tensorflowonspark/TFCluster.py
- tensorflowonspark/TFSparkNode.py
Adds a new timeout argument (default: 10 minutes) to `TFCluster.train()` and `TFCluster.inference()` for feeding an RDD partition to TensorFlow.  If the partition is not consumed within the timeout period, an Exception will be raised and Spark will retry this partition/task.
This helps to resolve deadlocks where the Spark feeding operation is blocked while waiting for the TF process to consume the data (which might be non-responsive for whatever reason).
> Introduce a feed timeout for InputMode.SPARK

- examples/mnist/keras/mnist_mlp_estimator.py
- tensorflowonspark/TFSparkNode.py
- only set TF_CONFIG if cluster_spec has a "master", i.e. using `tf.estimator`.
- example of distributed inferencing using `estimator.predict` w/ InputMode.SPARK.
Note: the `tf.estimator.train_and_evaluate` API provides an abstraction for both single-node AND distributed training, but there is no equivalent API for single-node and distributed inferencing.
This example uses "parallel" inferencing, where each Spark executor runs a single-node `tf.estimator.Estimator.predict()`.
> Distributed inferencing via estimator.predict

- examples/mnist/keras/README.md
- examples/mnist/keras/mnist_inference.py
- examples/mnist/keras/mnist_mlp_estimator.py
- examples/mnist/tf/README.md
Since this is the recommended path going forward...
- Updated mnist/keras/README.md
- Added saved_model_cli inferencing example
- Added tf-serving inferencing example
- Added parallel inferencing example
- Minor cleanup
> Default keras example to tf.estimator

- .travis.yml
- requirements.txt
> bump spark version

- tensorflowonspark/TFCluster.py
- tensorflowonspark/TFSparkNode.py
Summary of the change 
- When running tensorflow in distributed mode, sets up the evaluator node. 
- During shutdown, evaluator node is also shutdown similar to ps
> add evaluator node for distributed evaluation

- examples/wide_deep/README.md
... to ensure that models/official module is in PYTHONPATH.
> add instructions from tensorflow/models

- examples/mnist/spark/mnist_dist.py
... which was inadvertently removed in prior commits.
> add back code to terminate feed

- setup.py
... to allow variants like `tensorflow-gpu` and `tf-nightly` installations.
> remove tensorflow as explicit dependency

- .travis.yml
- requirements.txt
> update to spark 2.4.3

- .travis.yml
- docs/source/conf.py
- requirements.txt
> update to Spark 2.4.4; use sphinx_rtd_theme

- examples/mnist/keras/mnist_tf_ds.py
> fix data_format parsing; remove auto_shard option

- docs/source/conf.py
- pom.xml
- setup.py
- tensorflowonspark/__init__.py
> prepare v2.1.0 release

- docs/source/conf.py
- pom.xml
- setup.py
- tensorflowonspark/__init__.py
> v2.1.1 release

- docs/source/conf.py
- pom.xml
- setup.py
- tensorflowonspark/__init__.py
> v2.1.2 release

- docs/source/conf.py
- pom.xml
- setup.py
- tensorflowonspark/__init__.py
> prepare v2.1.3 release

- .travis.yml
> remove python2.7 build

- tensorflowonspark/compat.py
> update compat.export_saved_model to avoid file conflict errors

- .travis.yml
- tensorflowonspark/TFNode.py
- tensorflowonspark/TFSparkNode.py
Initial code to leverage Spark 3 GPU resource allocation.
> Spark3 GPU allocation

- scripts/travis_before_install.sh
> update to spark 2.4.5

- docs/source/conf.py
- pom.xml
- setup.py
- tensorflowonspark/__init__.py
> v2.2.0 release

- tensorflowonspark/TFSparkNode.py
- tensorflowonspark/gpu_info.py
- test/test_TFSparkNode.py
- test/test_reservation.py
> add unit tests for gpu allocation variants

- tensorflowonspark/TFSparkNode.py
- tensorflowonspark/util.py
also added msg to check for exceptions on other nodes
> added error msg for missing executor_id

- examples/mnist/keras/mnist_tf.py
> workaround for issue w/ tensorflow_datasets

- tensorflowonspark/reservation.py
- test/test_reservation.py
> support range for TFOS_SERVER_PORT

- docs/source/conf.py
- pom.xml
- setup.py
- tensorflowonspark/__init__.py
> v2.2.1 release

- examples/mnist/estimator/README.md
- examples/mnist/estimator/mnist_inference.py
- examples/mnist/keras/mnist_tf.py
- examples/resnet/README.md
- examples/resnet/resnet_cifar_dist.py
- examples/resnet/resnet_cifar_main.py
- examples/segmentation/README.md
> more updates to examples

- examples/mnist/estimator/README.md
- examples/mnist/keras/README.md
- examples/resnet/README.md
- examples/segmentation/README.md
- requirements.txt
- test/README.md
> update README docs to enable more automated tests of command lines

- scripts/travis_before_install.sh
> update to spark-2.4.6

- README.md
- screwdriver.yaml
- setup.cfg
> publish on tag; add packaging as requirement

- pom.xml
- requirements.txt
- scripts/install_spark.sh
> update python build for spark 3 dependencies

- docs/source/conf.py
- pom.xml
- tensorflowonspark/__init__.py
> v2.2.3 release

- setup.cfg
> update setup.cfg too

- .travis.settings.xml
- screwdriver.yaml
> more doc fixes

- screwdriver.yaml
> validate_safety -> validate_dependencies

- tests/test_TFCluster.py
> unit tests for release_port argument

- doc/source/conf.py
- pom.xml
- setup.cfg
- tensorflowonspark/__init__.py
> v2.2.4 release

- screwdriver.yaml
> disable PR builds
