yahoo/TensorFlowOnSpark

src/com/yahoo/ml/tf/TFSparkNode.py
That `HADOOP_PREFIX` is defined does not mean that `hadoop` is in `PATH`.
- use `HADOOP_PREFIX` to get the path to `hadoop`
=> Fix invalid usage of HADOOP_PREFIX

examples/cifar10/cifar10_eval.py, examples/cifar10/cifar10_multi_gpu_train.py, examples/cifar10/cifar10_train.py, examples/imagenet/inception/imagenet_distributed_train.py, examples/imagenet/inception/imagenet_eval.py, examples/mnist/spark/mnist_spark.py, examples/mnist/tf/mnist_spark.py, examples/slim/eval_image_classifier.py, examples/slim/train_image_classifier.py, src/com/yahoo/ml/tf/TFCluster.py, src/com/yahoo/ml/tf/TFSparkNode.py, src/com/yahoo/ml/tf/reservation.py
... which combines `reserve` and `start` steps into one call.
This starts a server on the driver to listen for reservations (replacing the `reserve` step). Each executor/node will then reserve a port, report it to the server, and then wait for all other executors to report before starting the TF process on the node.
This resolves:
- most of the "TFManager already started" issues, since the nodes will now block until all other nodes have responded with their port reservations (i.e. guaranteeing even distribution of "reserve" tasks across all executors).
- most of the "socket already in use" issues, since nodes will now hang onto the reserved socket until just prior to starting the TF process on each node (vs. releasing after the reserve step). Note: there's still a chance that another …
=> new TFCluster.run() api

src/com/yahoo/ml/tf/TFSparkNode.py
Generally speaking we set `PYSPARK_PYTHON` to `spark-env.sh`. It means that `PYSPARK_PYTHON` may be not in `os.environ`. This PR add extra `PATH` to find `tensorboard`. more see #61.
`PYTHONPATH` may looks like this:
```
'PYTHONPATH': '/opt/cloudera/parcels/2.1.0-2.6.0.d20170113-15.36.26/lib/spark/jars/spark-core_2.11-2.2.0-SNAPSHOT.jar:/opt/cloudera/parcels/Anaconda/bin/python::/opt/cloudera/parcels/Anaconda/bin/python:/data/M05/yarn/nm/usercache/tandem/appcache/application_1491988027269_1406/container_e55_1491988027269_1406_01_000004/__pyfiles__:/opt/cloudera/parcels/2.1.0-2.6.0.d20170113-15.36.26/lib/spark/python/lib/py4j-0.10.4-src.zip:/opt/cloudera/parcels/2.1.0-2.6.0.d20170113-15.36.26/lib/spark/python/lib/pyspark.zip:/data/M05/yarn/nm/usercache/tandem/appcache/application_1491988027 …
```
=> Add extra PATH to find tensorboard

README.md
Infiniband support has now been merged to tensorflow main repository.
=> remove reference to yahoo/tensorflow fork

tensorflowonspark/TFSparkNode.py, tensorflowonspark/reservation.py, tensorflowonspark/util.py
It is more reliable to use IP addresses to pass cluster specifications since they are more likely to be resolvable by other machines in the cluster (as opposed to socket hostnames). This PR replaces all instances of `socket.gethostname` with `util.get_ip_address`.
I have tested this with a distributed tensorflowonspark job and the job runs properly.
=> Use IP address instead of socket hostname

examples/imagenet/inception/imagenet_distributed_train_pipeline.py, examples/imagenet/inception/inception_export.py, tensorflowonspark/pipeline.py
Also, modified imagenet pipeline example to export `top_5_acc` instead of `logits`.
=> Cache session during pipeline inferencing

examples/mnist/spark/mnist_dist_dataset.py, examples/mnist/spark/mnist_spark_dataset.py, examples/mnist/tf/mnist_dist_dataset.py, examples/mnist/tf/mnist_spark_dataset.py, setup.py, tensorflowonspark/TFSparkNode.py, tensorflowonspark/util.py
- MNIST examples for InputMode.SPARK and InputMode.TENSORFLOW using TFRecords and CSV.
- Removes `--debug` flag from tensorboard (which conflicts with a new flag in 1.4).
- Added utility to look for tensorboard binary in multiple paths.
=> TF 1.4 datasets examples

examples/imagenet/inception/imagenet_distributed_train_pipeline.py, examples/mnist/spark/mnist_dist.py, examples/mnist/spark/mnist_spark.py, setup.py, tensorflowonspark/TFCluster.py, tensorflowonspark/TFSparkNode.py, tensorflowonspark/pipeline.py, tensorflowonspark/util.py
For Review Only.
- Merges TFNode functionality into the TFNodeContext object that's passed into the TensorFlow `map_fn`.
- Adds option to start the `tf.train.Server` before invoking the user's `map_fn`.
- Maintains backwards-compatibility for existing code.
- Removes deprecated APIs.
=> TFNode refactor

.gitmodules
This submodule was initially used for RDMA support, which is now merged into the main TensorFlow codebase, so it is no longer needed here.  
Note: will need to update some of the wiki docs after merge.
=> Remove tensorflow submodule

examples/model_export.py
Simple tool to aid creation of saved_model exports from checkpoint files, will be used in wiki examples.
=> add model_export tool

examples/mnist/spark/mnist_dist.py
tf.train.Supervisor is deprecated in tensorflow1.6, so I update it using tf.train.MonitoredTrainingSession.  Meanwhile, I update the usage of Tensorboard.
=> Update mnist_dist.py using tensorflow1.6

examples/criteo/README.md, examples/criteo/spark/criteo_dist.py, examples/criteo/spark/criteo_spark.py, examples/criteo/spark/requirements.txt
This is a pull request who aims at having an example solution  to learn click through rate at scale on the publicly available Criteo 1TB data set. The current post uses RDD with spark. I would like to integrate further examples using TF read approach as well.
=> add criteo example

tensorflowonspark/TFNode.py
This PR provides a fix for issue described here: https://github.com/yahoo/TensorFlowOnSpark/issues/275
=> Fixing an issue where parameter server always reserves 1 GPU as long as TensorFlow GPU build is used

.gitignore, pom.xml
Recent commits to tensorflow-ecosystem rendered TensorFlowOnSpark unbuildable: https://github.com/tensorflow/ecosystem/tree/master/hadoop
=> update tensorflow-hadoop dependency

tensorflowonspark/TFCluster.py
Construct tensorboard_url for the first node with non-zero tensorboard port. No need to process the rest of the list.
=> simplify tensorboard_url

examples/mnist/spark/mnist_dist.py, examples/mnist/spark/mnist_spark.py, tensorflowonspark/TFCluster.py
- add grace period to TFCluster.shutdown
- add ExportHook as a SessionRunHook example
=> Add shutdown grace period

tensorflowonspark/util.py
Currently there is an issue with get_ip_address method in utils.py file which prevents the driver from starting TF cluster. It does not work with corporate firewall proxy servers. Since it is making use of raw socket APIs, we can't use HTTP_PROXY also, even though the socket connection is to HTTP port. I am surprised that not many people ran into this issue  except the one mentioned in #208 where the person had to resort to using VMs on a single node instead of different physical nodes. 
I  ran into this issue in my lab and I had to fix it to try TFOS. 
This PR works around the issue by  catching the exception (ENETUNREACH - 101)  with proxy and tries gethostname with FQDN. Normally on Hadoop clusters FQDNs are used for all the nodes in the cluster, so this should work most of the times. …
=> Workaround for firewall proxy isue with get_ip_address

tensorflowonspark/TFNode.py
As of Hadoop 3.0.x there are a lot more Hadoop Compatible File Systems that are supported.
This PR adds support for the following URI schemes:
```
HADOOP_SCHEMES = ['adl://',
'hdfs://',
'oss://',
's3://',
's3a://',
's3n://',
'swift://',
'viewfs://',
'wasb://']
```
And corrects a very minor typo: `s/defaultSF/defaultFS/g`
=> Add support for all Hadoop-Compatible File System Schemes

.gitignore, .travis.yml, tensorflowonspark/pipeline.py, tensorflowonspark/reservation.py, test/test_reservation.py
While trying to run TFoS driver from a docker container I found out it getting reservation is getting blocked, due to the fact that reservation is using the container IP and a random PORT.
To allow using the host IP instead of the container IP and predetermined PORT I added this PR.
The container will listen to the PORT and we will bind all traffic from SERVER IP + PORT to container PORT
So if you are using docker container you need to add 2 environment variables:
TFOS_SERVER_SOCKET = the host of the container
TFOS_SERVER_HOST = port to bind to host
docker run -e TFOS_SERVER_SOCKET=4567 -e TFOS_SERVER_HOST=$HOST_IP -p 4567:4567 my_driver_image_name
=> Enable configuring TFoS server IP and PORT

examples/mnist/keras/mnist_mlp_estimator.py, pom.xml, tensorflowonspark/pipeline.py
... since `signature_def_utils.get_signature_def_by_key` is no longer available.  
Also adds workaround for TF21745 to mnist_mlp_estimator.py example.
=> Update pipeline.py to latest 1.12 API

tensorflowonspark/TFCluster.py, tensorflowonspark/TFNode.py, tensorflowonspark/TFSparkNode.py, tensorflowonspark/gpu_info.py
- more deterministic algo to avoid conflicts (based on original idea/code from @anttisaukko)
- added global timeout
=> GPU allocation

examples/mnist/tf/README.md, examples/mnist/tf/mnist_dist.py, examples/mnist/tf/mnist_inference.py, examples/mnist/tf/mnist_spark.py, tensorflowonspark/pipeline.py, tensorflowonspark/util.py
Also factor out `util.single_node_env()`.
=> Example for inferencing from saved_model

tensorflowonspark/TFSparkNode.py, tensorflowonspark/gpu_info.py
- set TF_CONFIG for 'chief' clusters (since DistributionStrategy does not use 'master')
- fix multi-gpu allocation
=> Support DistributionStrategy API

tensorflowonspark/pipeline.py
We have created a model which looks like this
```
signature_def['serving_default']:
The given SavedModel SignatureDef contains the following input(s):
inputs['dense_input'] tensor_info:
dtype: DT_FLOAT
shape: (-1, 179)
name: Placeholder:0
inputs['identity_input'] tensor_info:
dtype: DT_INT64
shape: (-1, 1)
name: Placeholder_1:0
The given SavedModel SignatureDef contains the following output(s):
outputs['identity_output'] tensor_info:
dtype: DT_FLOAT
shape: (-1, 1)
name: identity_output/identity_output/Identity:0
outputs['prediction'] tensor_info:
dtype: …
```
=> handle multiple outputs with signaturedef

README.md, examples/mnist/README.md
=> move TF version specific instructions from wiki to README

.tidelift.yml, docs/source/conf.py, setup.py, tensorflowonspark/__init__.py
=> v1.4.4 release

examples/mnist/keras/README.md, examples/mnist/keras/mnist_pipeline.py, examples/mnist/keras/mnist_tf.py, examples/segmentation/segmentation_spark.py
`load_weights_on_restart` is deprecated... and causes issues if set.
=> remove deprecated arg

tensorflowonspark/TFCluster.py, tensorflowonspark/TFNode.py, tensorflowonspark/TFSparkNode.py, tensorflowonspark/gpu_info.py, tensorflowonspark/pipeline.py, tensorflowonspark/reservation.py, tensorflowonspark/util.py, test/README.md
=> use module loggers

examples/mnist/estimator/README.md, examples/mnist/estimator/mnist_pipeline.py, examples/mnist/estimator/mnist_spark.py, examples/mnist/keras/README.md, examples/mnist/keras/mnist_pipeline.py, examples/mnist/keras/mnist_spark.py, examples/mnist/keras/mnist_tf.py, examples/mnist/keras/mnist_tf_ds.py, examples/segmentation/README.md, examples/segmentation/segmentation_spark.py, requirements.txt, tensorflowonspark/TFNode.py, tensorflowonspark/compat.py, tensorflowonspark/pipeline.py, test/test_pipeline.py
... and re-introduce compatibility w/ TF1.x APIs (except for InputMode.TENSORFLOW support in the ML Pipelines API... which is still no longer supported, since that API is driven from Spark DataFrames).
=> Add compat layer for TF2.1rc0 compatibility

examples/mnist/keras/mnist_tf.py, tensorflowonspark/TFSparkNode.py, tensorflowonspark/compat.py
=> Allow running tensorboard on chief/master, if no workers available

tensorflowonspark/TFNode.py, tensorflowonspark/TFSparkNode.py, tensorflowonspark/compat.py, tensorflowonspark/util.py, test/test_pipeline.py
- add compat.is_gpu_available()
- fix test failure
=> TF2.1 release compatibility

tensorflowonspark/compat.py, test/test_pipeline.py
To avoid `RuntimeError: Collective ops must be configured at program startup` when using `MultiWorkerMirroredStrategy`.
=> use list_physical_devices to avoid runtime initialization

examples/mnist/estimator/mnist_pipeline.py, examples/mnist/keras/mnist_pipeline.py, tensorflowonspark/TFNode.py
=> InputMode.SPARK perf optimization

tensorflowonspark/TFNode.py, tensorflowonspark/TFSparkNode.py, tensorflowonspark/gpu_info.py, tensorflowonspark/pipeline.py, tensorflowonspark/util.py, test/README.md
... to avoid gpu allocation issues.
=> detect TF version w/o importing

examples/mnist/estimator/mnist_inference.py, examples/mnist/keras/mnist_inference.py
In reference mode, we do manual sharding in each single-node TF instances, so we have to make sure we get input filenames in a deterministic order which is not the default behavior of method `tf.data.Dataset.list_files` according to [[TF doc]](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#list_files).
=> list_files in inference examples should be deterministically

tensorflowonspark/TFSparkNode.py, test/test_reservation.py
Executors will now use the following environment variables (if set) for selecting/binding to ports (where previously, they bound to random ports):
```
TENSORBOARD_PORT
TENSORFLOW_PORT
```
Additionally, the TFoS registration server address/ports were already configurable via [this PR](https://github.com/yahoo/TensorFlowOnSpark/pull/367):
```
TFOS_SERVER_HOST
TFOS_SERVER_PORT
```
=> configurable ports for TF and TensorBoard

tensorflowonspark/TFCluster.py, tensorflowonspark/TFSparkNode.py, tensorflowonspark/gpu_info.py
=> revised gpu allocation code

README.md
The previous link to the blog post pointed to the Tumblr blog, which is no longer there.
=> Update the link to the blog post

screwdriver.yaml, tensorflowonspark/TFCluster.py, tensorflowonspark/TFNode.py, tensorflowonspark/TFSparkNode.py, tests/test.py
- adds option to defer release of reserved/assigned port to user map_fn (instead of automatically releasing just prior invoking map_fn).
- trigger doc build after pypi publish.
=> allow deferred release of reserved port

tensorflowonspark/TFSparkNode.py, tests/test_TFSparkNode.py
=> use TaskContext.get to avoid creating instance in unit tests

tensorflowonspark/TFNode.py, tensorflowonspark/TFParallel.py, tensorflowonspark/TFSparkNode.py, tensorflowonspark/pipeline.py, tensorflowonspark/util.py, tests/test_TFSparkNode.py
Try to import `tensorflow-cpu` if `tensorflow` is not available.
=> minor patches
